### ISSUE TITLE
Consider classed list output of pixel data

### ISSUE THREAD

**Issue by ctoney** [USDAForestService/gdalraster#185]
@mdsumner suggested:
>I've been toying with a classed output of pixels from GDAL, but currently I use just a list with attributes: extent, dimension, projection - then with ximage::ximage it knows about that type of object (and a few others) and otherwise works with a 'rasterImage()' matrix or array with second argument "extent". This one thing has been probably the most clarifing move I've ever made in R, and helps me get the plots I want more than any other features in packages.

>I wish there was something basic and standard like that across R packages, ... but maybe we at least can find a common basis to use together! (I'm excited by gdalraster and hoping to use it to lever into even more of the GDAL API. )

>The other plotting feature I like (s2 has implemented this for its Orthographic plots) is recording the last crs used, it seems such a simple thing to do so that overplotting code can transform to the plot as needed. ximage also has xcontour but that needs a bit more to it

>Maybe we could agree on a lightly classed list output - that only records these essentials (extent, dimension, crs). I've toyed with having that only store the file name (so it's the same as a stars proxy in that case) and reading with GDAL to match the device in use for plotting, but it's all just experiments. Another small aspect that might be of interest, when it's just for visuals - I've found it simpler to read satellite imagery (Int16) and then convert to colours in R (with 'colourvalues') rather than have GDAL line up Sentinel bands and scale them, fwiw).

**Comment by ctoney** [comment]
@mdsumner Thanks for engaging on this. I'm realizing that `gdalraster::read_ds()` probably should have returned a list for multi-band output. But it could add an `as_list` argument and then return list with attributes. Or, it doesn't have to be a list always right? The standard attributes could be on vector, matrix or list?

**Comment by ctoney** [comment]
Also I've been looking at ximage in more detail. Understand what you're getting at. Good stuff there. I'm learning from it. Thanks again.

**Comment by mdsumner** [comment]
I've been experimenting with nativeRaster, in this side project and in ximage. It's really worthwhile I think, the nativeRaster is an R integer matrix, so it's slightly bigger than 3 raw bands, but way better than hex character strings. 

https://github.com/mdsumner/gdalnara/blob/main/src/gdalnara.cpp#L14-L15

(gdalnara is just a stripped down vapour for reading with GDALWarp)

I'll fold it into vapour and use it with ximage, but I recommend using it and it's pretty simple to do.

**Comment by ctoney** [comment]
@mdsumner PR #198 modifies the convenience function `read_ds()` so that output is optionally a list of band vectors (instead of single vector interleaved by band). It also attaches `gis` attribute.
`plot_raster()` is modified to accept list input (previously accepted vector or dataset object), and make use of `gis` attributes if present when the input is raw pixel data in a list or vector. Please let me know if you have comments or suggestions on the use of `gis` attribute.
