### ISSUE TITLE
Load data as integer

### ISSUE THREAD

**Issue by kadyb** [USDAForestService/gdalraster#23]
Great initiative! Would it be possible to add the feature of reading data as integer if the input raster is datatype of byte/int? This is supported by `{rgdal}`.

**Comment by ctoney** [comment]
Thanks for the feedback. Yes data should be read as integer when the raster datatype is integer, and the change is straightforward. I was intending to revisit at some point.  I would change read() to return integer type in that case rather than double as it currently does for both integer and floating point raster (and also read into integer buffer in the first place). Of course, integer in R will be 32-bit for raster that is 8/16/32-bit, but still half the size of double. Is that what you had in mind?

**Comment by kadyb** [comment]
Yes, exactly.

**Comment by ctoney** [comment]
Thanks. This should be addressed sometime soon, most likely before another version update to CRAN. I will leave the issue open and post a comment once I make the change.

**Comment by ctoney** [comment]
Commits were made in `main` for this. The `main` branch contains the development version, and the online documentation and change log reflect the current code.

Data are read as int32 when possible for the raster data type. Any differences in read performance are likely to be negligible, but the data as read in will occupy half as much memory for the common Byte/Int16/Int32 types. Testing appreciated.

**Comment by kadyb** [comment]
Thank you very much! I tested with the code below and everything works (sample data from the `{stars}` package). The only issue is maybe something can be improved in the `gdalraster_read()` function (maybe `abind::abind()`?), because for now it allocates more memory (according to `bench::mark()`) than `{stars}`.

<details>
<summary>Code</summary>

```r
library("gdalraster")

gdalraster_read = function(f) {
  ds = new(GDALRaster, f, read_only = TRUE)
  dm = c(ds$getRasterXSize(), ds$getRasterYSize())
  bands = ds$getRasterCount()
  ls = vector("list", bands)
  for (i in seq_len(bands)) {
    ls[[i]] = ds$read(i, 0, 0, dm[1], dm[2], dm[1], dm[2])
  }
  r = array(unlist(ls), dim = c(dm, bands))
  ds$close()
  return(r)
}

tif1 = system.file("tif/geomatrix.tif", package = "stars")
r1 = gdalraster_read(tif1)
typeof(r1)
#> [1] "integer"

tif2 = system.file("tif/lc.tif", package = "stars") # categorical raster
r2 = gdalraster_read(tif2)
typeof(r2)
#> [1] "integer"

tif3 = system.file("tif/L7_ETMs.tif", package = "stars")
r3 = gdalraster_read(tif3)
typeof(r3)
#> [1] "integer"

tif4 = system.file("tif/na.tif", package = "stars") # float32
r4 = gdalraster_read(tif4)
typeof(r4)
#> [1] "double"

bench::mark(
  check = FALSE,
  gdalraster = gdalraster_read(tif3),
  stars = read_stars(tif3)
)[, c(1, 5)]
#>   expression mem_alloc
#> 1 gdalraster    8.44MB
#> 2 stars         5.63MB
```

</details>

**Comment by ctoney** [comment]
Thanks for the additional testing. For memory usage I was looking at the size of the data after it has been read into a vector (using `object.size()`, results consistent with your check using `typeof()`). Reading directly into the array seems to change the memory allocation reported by `bench::mark()`. Can you confirm?

<details>
<summary>Code</summary>

```r
library("gdalraster")

gdalraster_read = function(f) {
  ds = new(GDALRaster, f, read_only = TRUE)
  dm = c(ds$getRasterXSize(), ds$getRasterYSize())
  bands = ds$getRasterCount()
  r = array(NA_integer_, dim = c(dm, bands))
  for (i in seq_len(bands)) {
    r[,,i] = ds$read(i, 0, 0, dm[1], dm[2], dm[1], dm[2])
  }
  ds$close()
  return(r)
}

tif3 = system.file("tif/L7_ETMs.tif", package = "stars")
r3 = gdalraster_read(tif3)

object.size(r3)
#> 2948576 bytes

library(stars)

r3_stars = read_stars(tif3, proxy = FALSE)

object.size(r3_stars)
#> 5908744 bytes

bench::mark(
  check = FALSE,
  gdalraster = gdalraster_read(tif3),
  stars = read_stars(tif3)
)[, c(1, 5)]
#>   expression mem_alloc
#> 1 gdalraster    5.64MB
#> 2 stars         5.63MB
```

</details>

**Comment by kadyb** [comment]
Yes, after this change I see that the memory allocation is the same as in `{stars}`, but the array finally takes half the memory. Thanks!
