### ISSUE TITLE
ogr_ds_create clobbers existing file

### ISSUE THREAD

**Issue by mdsumner** [USDAForestService/gdalraster#400]
I was half expecting this to work to open an existing data set, but it clobbers it with no checking of file exist or use of read/update mode.

```R
src <- system.file("extdata/ynp_fires_1984_2022.gpkg", package="gdalraster")
ogr_ds_layer_count(src)
# [1]
file.copy(src, tf <- file.path(tempdir(), basename(src)))
ogr_ds_create("GPKG", tf)
ogr_ds_layer_count(tf)
# [0]
```

This should fail on file.exists test, with `ogr_ds_exists()` safety valve?

**Comment by ctoney** [comment]
Thanks! #401 adds a param for `overwrite` and does the check.
