### ISSUE TITLE
read orientation

### ISSUE THREAD

**Issue by mdsumner** [USDAForestService/gdalraster#5]
hi! nice to see a serious effort at a GDAL bindings for R :) I look forward to learning from your implemention! 

The orientation of a read is interleaved with the y/x flipped in the push to matrix

``` r
#dsn::gebco()
#[1] "/vsicurl/https://gebco2023.s3.valeria.science/gebco_2023_land_cog.tif"
library(gdalraster)
#> GDAL 3.8.0dev-0ae885e6d8-dirty, released 2023/05/10 (debug build)
ds <- new(GDALRaster, "/vsicurl/https://gebco2023.s3.valeria.science/gebco_2023_land_cog.tif", TRUE)
dm <- c(ds$getRasterXSize(), ds$getRasterYSize())
x <- ds$read(1L, 0, 0, dm[1L], dm[2L], 256, 128)

bb <- ds$bbox() 
plot(NA, xlim = bb[c(1, 3)], ylim = bb[c(2, 4)])
rasterImage(scales::rescale(x), bb[1], bb[2], bb[3], bb[4])
```

![](https://i.imgur.com/t33qOnN.png)

<sup>Created on 2023-05-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Get the correct visual orientation with 

```R
plot(NA, xlim = bb[c(1, 3)], ylim = bb[c(2, 4)])
rasterImage(scales::rescale(matrix(x, nrow(x), byrow = TRUE)), bb[1], bb[2], bb[3], bb[4])
```

It's simple to flip `Rcpp::Dimension(out_xsize, out_ysize);` in gdalraster.cpp but, I'd like to make a plea to avoid returning dimensioned output, or at least provide another layer to avoid doing so. The GDAL API more naturally (IMO) returns a dimensionless buffer whose orientation and dimension we already know, and R has a problematic mix of array orientations with 'rasterImage' being arguably more helpful than that of 'image'. 

Personally, I have moved to using dimensionless output (from topleft, by row then down GDAL pixel/line convention) in the order gdal returns it (this order was used by sp, raster, sf, and vapour) and the push into a matrix with this convention: 

```R
## *lines* because nrow/ncol is often flipped in R for various conventions
matrix(dat, nlines, byrow = TRUE)
```

and use that downstream as appropriate for rasterImage, and not as an ongoing orientation.  (I wrap that up in hypertidy/ximage for using the output of `vapour::gdal_raster_data/image` for example). 

I don't want to thrust my own packages and idioms onto your project, but I've found this separation to be a very important one and hope you're interested to explore/discuss. Thanks!!

**Comment by ctoney** [comment]
Thanks. I made a commit with the change. Does that look right? I agree dimensionless output is probably better.  I'll consider that more and take a look at "hypertidy/ximage for using the output of vapour::gdal_raster_data/image".  I was not familiar with that.

**Comment by mdsumner** [comment]
Looks good to me, just consider that for rasterImage you need to transpose, and for image it's flipped vertically  (this is why I think dimensionless is best, because the rasterImage orientation is unexpected from a R matrix convention and we end up with a confusing mix). This does my head in, but fwiw I really want to get the lower level tools right  (moar power) before having total formality over visualization and so on.  When it's dimensionless you do 'matrix(vals, ncol, byrow = TRUE)` and transpose that and flatten to reverse.  

Here is a few examples that might give a flavour of what I've been thinking about  - {dsn} has online sources, {ximage} does plotting in a way I like and understands newish vapour warper output. I've also experimented with open datasets with externalptr and without Rcpp  but it's very very early for that stuff.  


``` r
  #remotes::install_github("hypertidy/dsn")     ## just a bunch of online sources, and some DSN helpers
#remotes::install_github("hypertidy/ximage")  ## a helper for rasterImage(), like image() or terra::plot()

library(gdalraster)
#> GDAL 3.8.0dev-0ae885e6d8-dirty, released 2023/05/10 (debug build)
dsn1 <- dsn::wms_arcgis_mapserver_ESRI.WorldImagery_tms()

ds <- new(GDALRaster, dsn1, read_only = TRUE)

## source spec
srcdm <- c(ds$getRasterXSize(), ds$getRasterYSize()) 
## target spec
dm <- dev.size("px")
ext <- ds$bbox()[c(1, 3, 2, 4)]

## 1) here I'm targeting making an image from a hex character vector (could do in C++, or use nativeRaster)
vals <- lapply(1:3, function(.band) ds$read(.band, 0L, 0L, srcdm[1L], srcdm[2L], dm[1L], dm[2]))
## actual colours
col <- do.call(rgb, c(vals, list(maxColorValue = 255)))

ximage::ximage(matrix(col, dm[2L], byrow = TRUE), extent = ext)
```

![](https://i.imgur.com/IDc1YUE.png)

``` r
ds$close()

## 2) here I'm simulating the output of vapour::gdal_raster_data/gdal_raster_image which
## I've been experimenting with (classes are good but I'd like to cogitate on the design more)
dsn2 <- dsn::gebco23()

ds2 <- new(GDALRaster, dsn2, read_only = TRUE)
ele <- ds2$read(1L, 0, 0, ds2$getRasterXSize(), ds2$getRasterYSize(), 360, 180)

## output is an R matrix, i.e. it goes down the columns not across rows
l <- structure(list(as.vector(ele)), 
               extent = ds2$bbox()[c(1, 3, 2, 4)], 
               dimension = dim(ele), 
               projection = ds2$getProjectionRef())

## informally, ximage knows about the output from vapour
ximage::ximage(l)
```

![](https://i.imgur.com/NX0kpdi.png)

``` r

## 3) showing off the vapour warp approach a bit (it's not ideal, I'm trying to learn how to get a proper GDAL API for R!)
## let's match the output we got from the above image tile server 
x2 <- vapour::gdal_raster_data(dsn2, target_crs = "EPSG:3857", 
                               target_dim = dm, target_ext = ext)

par(mfrow = c(2, 1), mar = rep(0, 4))
ximage::ximage(matrix(col, dm[2L], byrow = TRUE), extent = ext, asp = 1)
ximage::ximage(x2, asp = 1)
```

![](https://i.imgur.com/8Z9ehKy.png)

<sup>Created on 2023-05-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ctoney** [comment]
Thanks again. Very interesting and helpful. I'll look through it in more detail soon and would be glad to discuss more. I'll be making a commit for write also.

**Comment by ctoney** [comment]
I am going to switch to vector output from read() instead of matrix. The pixel order stays the same as what would be expected, but the user will need to dimension as matrix if necessary (e.g., display). As you point out, this better matches the concept of a GDAL-like interface. It also doesn't affect other code in gdalraster which only needs output as vector anyway. I may add some example code later to show matrix dimension, display, etc.   I'll touch base with you if I do. I don't do much display in R so your feedback above on that is much appreciated.

**Comment by mdsumner** [comment]
orientation now is good, I'd updated my working examples to this flat return type and forgot to report back 👌
